# Generated by Django 5.1.5 on 2025-02-05 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Log",
            fields=[
                ("log_id", models.AutoField(primary_key=True, serialize=False)),
                ("user_id", models.CharField(max_length=255)),
                ("action_type", models.CharField(max_length=100)),
                ("details", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
